"""Vector contour terrain for the Strategist's Map: same height field as terrain.py (seed 1966),
traced with marching squares into SVG polylines, smoothed (Chaikin) and simplified (RDP).
Origin: generated by this script; no external imagery."""
import numpy as np, math
from PIL import Image
W, H = 2400, 1500
GX, GY = 241, 151                       # grid nodes, 10 map units per cell
rng = np.random.default_rng(1966)
y, x = np.mgrid[0:GY, 0:GX].astype(np.float64)
x /= (GX - 1); y /= (GY - 1)
def hill(cx, cy, r, a): return a * np.exp(-(((x - cx) ** 2) + ((y - cy) * 0.62) ** 2) / (r * r))
f = (hill(.86, .2, .2, 1.0) + hill(.62, .35, .14, .55) + hill(.42, .62, .13, .42) +
     hill(.2, .82, .1, .22) + hill(.74, .62, .1, .38) + hill(.3, .3, .12, .3) + .55 * (1 - y) * x)
def noise(scale, amp):
    g = rng.standard_normal((int(scale * .62) + 3, scale + 3)).astype(np.float32)
    return amp * np.array(Image.fromarray(g).resize((GX, GY), Image.BICUBIC), dtype=np.float64)
for sc, a in ((5, .05), (11, .028), (23, .014), (47, .007)): f += noise(sc, a)
f -= .12 * np.exp(-((x - .55 - .1 * np.sin(y * 6)) ** 2) / .0018)
f = (f - f.min()) / (f.max() - f.min())
sx, sy = W / (GX - 1), H / (GY - 1)

def segments(level):
    segs = []
    v = f
    for j in range(GY - 1):
        for i in range(GX - 1):
            a, b, c, d = v[j, i], v[j, i + 1], v[j + 1, i + 1], v[j + 1, i]
            idx = (a > level) | ((b > level) << 1) | ((c > level) << 2) | ((d > level) << 3)
            if idx in (0, 15): continue
            def lerp(p, q, vp, vq): t = (level - vp) / (vq - vp); return (p[0] + (q[0] - p[0]) * t, p[1] + (q[1] - p[1]) * t)
            A, B, C, D = (i, j), (i + 1, j), (i + 1, j + 1), (i, j + 1)
            top = lerp(A, B, a, b); right = lerp(B, C, b, c); bot = lerp(D, C, d, c); left = lerp(A, D, a, d)
            table = {1: [(left, top)], 2: [(top, right)], 3: [(left, right)], 4: [(right, bot)], 5: [(left, top), (right, bot)],
                     6: [(top, bot)], 7: [(left, bot)], 8: [(bot, left)], 9: [(bot, top)], 10: [(top, right), (bot, left)],
                     11: [(bot, right)], 12: [(right, left)], 13: [(right, top)], 14: [(top, left)]}
            segs += table[int(idx)]
    return segs

def chain(segs):
    key = lambda p: (round(p[0], 4), round(p[1], 4))
    adj = {}
    for s in segs:
        for p, q in (s, s[::-1]): adj.setdefault(key(p), []).append(q)
    used, lines = set(), []
    for s in segs:
        k = (key(s[0]), key(s[1]))
        if k in used: continue
        line = [s[0], s[1]]; used.add(k); used.add(k[::-1])
        for end in (1, 0):
            while True:
                tail = line[-1] if end else line[0]
                nxt = None
                for q in adj.get(key(tail), []):
                    kk = (key(tail), key(q))
                    if kk not in used: nxt = q; used.add(kk); used.add(kk[::-1]); break
                if nxt is None: break
                if end: line.append(nxt)
                else: line.insert(0, nxt)
        lines.append(line)
    return lines

def rdp(pts, eps):
    if len(pts) < 3: return pts
    a, b = np.array(pts[0]), np.array(pts[-1]); ab = b - a; n = np.hypot(*ab) or 1e-9
    d = [abs(np.cross(ab, np.array(p) - a)) / n for p in pts[1:-1]]
    i = int(np.argmax(d)) + 1
    if d[i - 1] > eps: return rdp(pts[:i + 1], eps)[:-1] + rdp(pts[i:], eps)
    return [pts[0], pts[-1]]

def chaikin(pts, n=2):
    for _ in range(n):
        out = [pts[0]]
        for p, q in zip(pts, pts[1:]):
            out += [(.75 * p[0] + .25 * q[0], .75 * p[1] + .25 * q[1]), (.25 * p[0] + .75 * q[0], .25 * p[1] + .75 * q[1])]
        out.append(pts[-1]); pts = out
    return pts

N = 30
minor, major = [], []
for k in range(1, N):
    lv = k / N
    for line in chain(segments(lv)):
        pts = [(p[0] * sx, p[1] * sy) for p in line]
        if len(pts) < 4: continue
        pts = chaikin(rdp(pts, 1.2), 2)
        d = "M" + " ".join(f"{p[0]:.0f} {p[1]:.0f}" for p in pts)
        (major if k % 5 == 0 else minor).append(d)
svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">'
       f'<path d="{"".join(minor)}" fill="none" stroke="#B6C4BE" stroke-opacity=".30" stroke-width="1.6"/>'
       f'<path d="{"".join(major)}" fill="none" stroke="#B6C4BE" stroke-opacity=".55" stroke-width="2.6"/></svg>')
open(__import__("os").path.join(__import__("os").path.dirname(__import__("os").path.dirname(__import__("os").path.abspath(__file__))), "images", "map", "terrain.svg"), "w").write(svg)
print(len(svg) // 1024, "KB,", len(minor), "minor,", len(major), "major")
